-- SiteInspect Supabase schema. Run once in Supabase SQL Editor.
create extension if not exists pgcrypto;
create type public.app_role as enum ('CONTRACTOR','PMC','CLIENT','ADMIN','SUPER_ADMIN');
create type public.company_type as enum ('CONTRACTOR','PMC','CLIENT');
create type public.inspection_status as enum ('DRAFT','PENDING_PMC','PMC_REJECTED','PENDING_CLIENT','CLIENT_REJECTED','FINAL_APPROVED','RESUBMITTED','CLOSED');
create type public.review_stage as enum ('PMC','CLIENT');
create type public.decision as enum ('APPROVED','REJECTED');
create type public.image_stage as enum ('CONTRACTOR','PMC','CLIENT');

create table public.companies(id uuid primary key default gen_random_uuid(),name text not null,code text unique,type company_type not null,is_active boolean not null default true,created_at timestamptz not null default now());
create table public.profiles(id uuid primary key references auth.users(id) on delete restrict,email text unique not null,name text not null,phone text,role app_role not null,company_id uuid references public.companies(id),is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.projects(id uuid primary key default gen_random_uuid(),name text not null,code text not null unique,address text,start_date date,end_date date,status text not null default 'ACTIVE',client_company_id uuid references companies(id),pmc_company_id uuid references companies(id),created_at timestamptz not null default now());
create table public.project_users(project_id uuid references projects(id) on delete cascade,user_id uuid references profiles(id) on delete cascade,created_at timestamptz not null default now(),primary key(project_id,user_id));
create table public.project_companies(project_id uuid references projects(id) on delete cascade,company_id uuid references companies(id) on delete cascade,primary key(project_id,company_id));
create table public.categories(id uuid primary key default gen_random_uuid(),name text not null unique,sort_order int not null default 0,is_active boolean not null default true,created_at timestamptz not null default now());
create table public.subcategories(id uuid primary key default gen_random_uuid(),category_id uuid not null references categories(id) on delete restrict,name text not null,sort_order int not null default 0,is_active boolean not null default true,created_at timestamptz not null default now(),unique(category_id,name));
create sequence if not exists public.inspection_seq;
create table public.inspections(id uuid primary key default gen_random_uuid(),inspection_number text not null unique,project_id uuid not null references projects(id),contractor_id uuid not null references profiles(id),category_id uuid not null references categories(id),subcategory_id uuid not null references subcategories(id),location text not null,status inspection_status not null default 'DRAFT',current_revision int not null default 0,lock_version int not null default 0,submitted_at timestamptz,final_approved_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.inspection_revisions(id uuid primary key default gen_random_uuid(),inspection_id uuid not null references inspections(id) on delete restrict,revision_no int not null,description text not null,submitted_by uuid not null references profiles(id),submitted_at timestamptz not null default now(),created_at timestamptz not null default now(),unique(inspection_id,revision_no));
create table public.inspection_images(id uuid primary key default gen_random_uuid(),inspection_id uuid not null references inspections(id) on delete restrict,revision_id uuid references inspection_revisions(id) on delete restrict,review_id uuid,stage image_stage not null,uploaded_by uuid not null references profiles(id),storage_key text not null unique,watermarked_storage_key text,original_filename text not null,mime_type text not null,size_bytes bigint not null,uploaded_at timestamptz not null default now());
create table public.reviews(id uuid primary key default gen_random_uuid(),inspection_id uuid not null references inspections(id) on delete restrict,revision_id uuid not null references inspection_revisions(id),stage review_stage not null,reviewer_id uuid not null references profiles(id),decision decision not null,comments text not null,rejection_reason text,previous_status inspection_status not null,new_status inspection_status not null,reviewed_at timestamptz not null default now(),created_at timestamptz not null default now(),unique(inspection_id,revision_id,stage));
alter table public.inspection_images add constraint inspection_images_review_fk foreign key(review_id) references reviews(id) on delete restrict;
create table public.inspection_events(id bigserial primary key,inspection_id uuid not null references inspections(id) on delete restrict,revision_id uuid references inspection_revisions(id),actor_id uuid not null references profiles(id),actor_name text not null,actor_role app_role not null,action text not null,previous_status inspection_status,new_status inspection_status,details jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table public.notifications(id uuid primary key default gen_random_uuid(),user_id uuid not null references profiles(id) on delete cascade,inspection_id uuid references inspections(id),title text not null,message text not null,read_at timestamptz,created_at timestamptz not null default now());
create table public.audit_logs(id bigserial primary key,user_id uuid references profiles(id),user_name_snapshot text,role_snapshot app_role,action text not null,entity_type text not null,entity_id text,previous_state jsonb,new_state jsonb,ip_address inet,user_agent text,created_at timestamptz not null default now());
create table public.app_settings(key text primary key,value jsonb not null,updated_by uuid references profiles(id),updated_at timestamptz not null default now());
create index inspections_project_idx on inspections(project_id);create index inspections_contractor_idx on inspections(contractor_id);create index inspections_status_idx on inspections(status);create index inspections_category_idx on inspections(category_id);create index inspections_created_idx on inspections(created_at desc);create index events_inspection_idx on inspection_events(inspection_id,created_at);create index reviews_reviewer_idx on reviews(reviewer_id,reviewed_at desc);create index notifications_user_idx on notifications(user_id,created_at desc);

create or replace function public.set_updated_at() returns trigger language plpgsql as $$begin new.updated_at=now();return new;end$$;
create trigger profiles_updated before update on profiles for each row execute function set_updated_at();create trigger inspections_updated before update on inspections for each row execute function set_updated_at();
create or replace function public.new_inspection_number() returns text language plpgsql security definer set search_path=public as $$declare n bigint;begin n:=nextval('public.inspection_seq');return 'INS-'||to_char(now() at time zone 'Asia/Kolkata','YYYY')||'-'||lpad(n::text,6,'0');end$$;

create or replace function public.submit_inspection(p_project uuid,p_category uuid,p_subcategory uuid,p_location text,p_description text,p_storage_keys text[],p_names text[],p_mimes text[],p_sizes bigint[]) returns uuid language plpgsql security definer set search_path=public as $$declare uid uuid:=auth.uid();iid uuid;rid uuid;i int;prof profiles%rowtype;begin select * into prof from profiles where id=uid and is_active=true;if prof.role<>'CONTRACTOR' then raise exception 'Only Contractor can create inspections';end if;if not exists(select 1 from project_users where user_id=uid and project_id=p_project) then raise exception 'Project access denied';end if;if trim(p_location)='' or trim(p_description)='' or coalesce(array_length(p_storage_keys,1),0)<1 then raise exception 'Required fields/photos missing';end if;if not exists(select 1 from categories where id=p_category and is_active) or not exists(select 1 from subcategories where id=p_subcategory and category_id=p_category and is_active) then raise exception 'Invalid category/subcategory';end if;insert into inspections(inspection_number,project_id,contractor_id,category_id,subcategory_id,location,status,current_revision,submitted_at) values(new_inspection_number(),p_project,uid,p_category,p_subcategory,p_location,'PENDING_PMC',0,now()) returning id into iid;insert into inspection_revisions(inspection_id,revision_no,description,submitted_by) values(iid,0,p_description,uid) returning id into rid;for i in 1..array_length(p_storage_keys,1) loop insert into inspection_images(inspection_id,revision_id,stage,uploaded_by,storage_key,original_filename,mime_type,size_bytes) values(iid,rid,'CONTRACTOR',uid,p_storage_keys[i],p_names[i],p_mimes[i],p_sizes[i]);end loop;insert into inspection_events(inspection_id,revision_id,actor_id,actor_name,actor_role,action,new_status) values(iid,rid,uid,prof.name,prof.role,'SUBMIT_INSPECTION','PENDING_PMC');return iid;end$$;

create or replace function public.review_inspection(p_inspection uuid,p_stage review_stage,p_decision decision,p_comments text,p_reason text,p_expected_version int,p_storage_keys text[],p_names text[],p_mimes text[],p_sizes bigint[]) returns void language plpgsql security definer set search_path=public as $$declare uid uuid:=auth.uid();prof profiles%rowtype;ins inspections%rowtype;rid uuid;ns inspection_status;i int;begin select * into prof from profiles where id=uid and is_active=true;select * into ins from inspections where id=p_inspection for update;if not found then raise exception 'Inspection not found';end if;if ins.lock_version<>p_expected_version then raise exception 'This inspection has already been reviewed. Refresh to see the latest status.';end if;if not exists(select 1 from project_users where user_id=uid and project_id=ins.project_id) and prof.role not in ('ADMIN','SUPER_ADMIN') then raise exception 'Project access denied';end if;if trim(p_comments)='' or coalesce(array_length(p_storage_keys,1),0)<1 then raise exception 'Comments and review photo required';end if;if p_stage='PMC' then if prof.role not in ('PMC','ADMIN','SUPER_ADMIN') or ins.status not in ('PENDING_PMC','RESUBMITTED') then raise exception 'Invalid PMC review';end if;ns:=case when p_decision='APPROVED' then 'PENDING_CLIENT' else 'PMC_REJECTED' end;else if prof.role not in ('CLIENT','ADMIN','SUPER_ADMIN') or ins.status<>'PENDING_CLIENT' then raise exception 'Invalid Client review';end if;ns:=case when p_decision='APPROVED' then 'FINAL_APPROVED' else 'CLIENT_REJECTED' end;end if;select id into rid from inspection_revisions where inspection_id=ins.id and revision_no=ins.current_revision;insert into reviews(inspection_id,revision_id,stage,reviewer_id,decision,comments,rejection_reason,previous_status,new_status) values(ins.id,rid,p_stage,uid,p_decision,p_comments,nullif(trim(p_reason),''),ins.status,ns);for i in 1..array_length(p_storage_keys,1) loop insert into inspection_images(inspection_id,revision_id,stage,uploaded_by,storage_key,original_filename,mime_type,size_bytes) values(ins.id,rid,p_stage::text::image_stage,uid,p_storage_keys[i],p_names[i],p_mimes[i],p_sizes[i]);end loop;update inspections set status=ns,lock_version=lock_version+1,final_approved_at=case when ns='FINAL_APPROVED' then now() else final_approved_at end where id=ins.id;insert into inspection_events(inspection_id,revision_id,actor_id,actor_name,actor_role,action,previous_status,new_status,details) values(ins.id,rid,uid,prof.name,prof.role,p_stage::text||'_'||p_decision::text,ins.status,ns,jsonb_build_object('comments',p_comments,'reason',p_reason));end$$;

create or replace function public.resubmit_inspection(p_inspection uuid,p_description text,p_storage_keys text[],p_names text[],p_mimes text[],p_sizes bigint[]) returns void language plpgsql security definer set search_path=public as $$declare uid uuid:=auth.uid();prof profiles%rowtype;ins inspections%rowtype;rid uuid;rev int;i int;begin select * into prof from profiles where id=uid and is_active;select * into ins from inspections where id=p_inspection for update;if ins.contractor_id<>uid or ins.status not in ('PMC_REJECTED','CLIENT_REJECTED') then raise exception 'Resubmission not allowed';end if;if trim(p_description)='' or coalesce(array_length(p_storage_keys,1),0)<1 then raise exception 'Comments and photo required';end if;rev:=ins.current_revision+1;insert into inspection_revisions(inspection_id,revision_no,description,submitted_by) values(ins.id,rev,p_description,uid) returning id into rid;for i in 1..array_length(p_storage_keys,1) loop insert into inspection_images(inspection_id,revision_id,stage,uploaded_by,storage_key,original_filename,mime_type,size_bytes) values(ins.id,rid,'CONTRACTOR',uid,p_storage_keys[i],p_names[i],p_mimes[i],p_sizes[i]);end loop;update inspections set current_revision=rev,status='RESUBMITTED',lock_version=lock_version+1 where id=ins.id;insert into inspection_events(inspection_id,revision_id,actor_id,actor_name,actor_role,action,previous_status,new_status) values(ins.id,rid,uid,prof.name,prof.role,'RESUBMIT_INSPECTION',ins.status,'RESUBMITTED');end$$;
