import { requireUser } from "@/lib/auth/guard";
import { AppShell } from "@/components/app-shell";

export const dynamic = "force-dynamic";

export default async function Page() {
  const u = await requireUser(["ADMIN", "SUPER_ADMIN"]);
  const [{ data: users }, { data: companies }] = await Promise.all([
    u.supabase.from("profiles").select("id,name,email,role,phone,is_active,company_id,companies(name)").order("created_at", { ascending: false }),
    u.supabase.from("companies").select("id,name").eq("is_active", true).order("name")
  ]);

  return <AppShell user={u.profile}>
    <div className="pagehead"><div><p className="eyebrow">Administration</p><h1>Users</h1><p className="muted">Create users quickly, then expand any row to view or edit details.</p></div><a className="btn btn-primary" href="#create-user">Create user</a></div>
    <section className="card formgrid" id="create-user"><div><p className="eyebrow">New access</p><h2>Create user</h2><p className="muted">Projects are shared across the workspace, so no project assignment is needed.</p></div><form className="formgrid" action="/api/admin/users" method="post"><div className="field"><label>Name</label><input name="name" required /></div><div className="field"><label>Email</label><input type="email" name="email" required /></div><div className="field"><label>Phone</label><input name="phone" /></div><div className="field"><label>Temporary password</label><input type="password" name="password" minLength={12} required /></div><div className="field"><label>Role</label><select name="role"><option>CONTRACTOR</option><option>PMC</option><option>CLIENT</option><option>ADMIN</option></select></div><div className="field"><label>Company</label><select name="companyId"><option value="">None</option>{companies?.map((company: any) => <option key={company.id} value={company.id}>{company.name}</option>)}</select></div><button className="btn btn-primary">Create user</button></form></section>
    <section className="card"><div className="section-heading"><div><p className="eyebrow">Directory</p><h2>All users</h2></div><span className="badge">{users?.length || 0} records</span></div><div className="liststack">{users?.map((user: any) => <details className="expand-row" key={user.id}><summary><span><strong>{user.name}</strong><small>{user.email} · {user.role}</small></span><span className="summary-action">View / edit</span></summary><div className="expand-body"><div className="detail-copy"><span className="eyebrow">User profile</span><h3>{user.name}</h3><p className="muted">{user.email} · {user.companies?.name || "No company"} · {user.is_active ? "Active" : "Disabled"}</p><a className="text-link" href={`/admin/users/${user.id}`}>Open full details</a></div><form className="inline-edit" action="/api/admin/users" method="post"><input type="hidden" name="action" value="update" /><input type="hidden" name="id" value={user.id} /><div className="field"><label>Name</label><input name="name" defaultValue={user.name} required /></div><div className="field"><label>Email</label><input type="email" name="email" defaultValue={user.email} required /></div><div className="field"><label>Phone</label><input name="phone" defaultValue={user.phone || ""} /></div><div className="field"><label>Role</label><select name="role" defaultValue={user.role}><option>CONTRACTOR</option><option>PMC</option><option>CLIENT</option><option>ADMIN</option></select></div><div className="field"><label>Company</label><select name="companyId" defaultValue={user.company_id || ""}><option value="">None</option>{companies?.map((company: any) => <option key={company.id} value={company.id}>{company.name}</option>)}</select></div><button className="btn btn-primary">Save changes</button></form><form action="/api/admin/users" method="post"><input type="hidden" name="action" value="delete" /><input type="hidden" name="id" value={user.id} /><button className="btn btn-danger">Delete user</button></form></div></details>)}</div></section>
  </AppShell>;
}
