import { AdminForm } from "@/components/admin-form";
import { requireUser } from "@/lib/auth/guard";
import { AppShell } from "@/components/app-shell";
import { WorkflowDeliveryForm } from "@/components/workflow-delivery-form";

export const dynamic = "force-dynamic";

export default async function Page({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const user = await requireUser(["ADMIN"]);
  const params = await searchParams;
  const { data } = await user.supabase.from("app_settings").select("value").eq("key", "smtp").maybeSingle();
  const { data: website } = await user.supabase.from("app_settings").select("value").eq("key", "public_app_url").maybeSingle();
  const { data: deliveries, error: deliveryError } = await user.supabase.from("audit_logs").select("id,action,entity_id,created_at,new_state").in("action", ["INSPECTION_EMAIL_SENT", "INSPECTION_EMAIL_FAILED", "REPORT_EMAIL_SENT", "REPORT_EMAIL_FAILED"]).order("created_at", { ascending: false }).limit(30);
  const { password, ...smtp } = (data?.value || {}) as Record<string, any>;
  return <AppShell user={user.profile}><div className="pagehead"><div><p className="eyebrow">Administration</p><h1>Workflow delivery</h1><p className="muted">Manage status emails and verify the SMTP connection.</p></div></div><section className="card"><h2>Public website address</h2><p>Enter the deployed HTTPS website address used in inspection email links.</p><AdminForm action="/api/admin/workflow" method="post"><input type="hidden" name="action" value="website" /><div className="field"><label>Website URL</label><input name="publicUrl" type="url" placeholder="https://inspections.example.com" defaultValue={website?.value?.url || process.env.NEXT_PUBLIC_APP_URL || ""} required /></div><button className="btn btn-primary">Save website address</button></AdminForm></section><WorkflowDeliveryForm smtp={{ ...smtp, hasPassword: Boolean(password) }} saveStatus={typeof params.test === "string" ? params.test : ""} saveReason={typeof params.reason === "string" ? params.reason : ""} /><section className="card"><h2>Email delivery history</h2><p className="muted">Mail-server acceptance is recorded for each attempt. Inbox delivery depends on the recipient’s mail service. Failed inspection reports can be retried here.</p>{deliveryError && <p className="error">Unable to load delivery history.</p>}{!deliveries?.length && !deliveryError && <p>No delivery attempts recorded yet.</p>}<div className="liststack">{deliveries?.map((log: any) => <div className="delivery-log" key={log.id}><div><strong>{log.new_state?.title || "Inspection report"}</strong><p>{new Date(log.created_at).toLocaleString("en-IN", {timeZone:"Asia/Kolkata"})} IST · {log.action.endsWith("FAILED") ? "Needs attention" : "Accepted by mail server"}</p><small>Accepted: {log.new_state?.accepted?.join(", ") || "None"}</small>{log.new_state?.rejected?.length > 0 && <small>Failed: {log.new_state.rejected.join(", ")}</small>}{log.new_state?.error && <p className="error">{log.new_state.error}</p>}</div>{log.action === "INSPECTION_EMAIL_FAILED" && log.entity_id && !log.new_state?.retried_at && <AdminForm action="/api/admin/workflow" method="post"><input type="hidden" name="action" value="retryInspection" /><input type="hidden" name="logId" value={log.id} /><button className="btn btn-secondary">Retry failed recipients</button></AdminForm>}</div>)}</div></section></AppShell>;
}
