import { DownloadButton } from "@/components/download-button";
import { AdminForm } from "@/components/admin-form";
import { requireUser } from "@/lib/auth/guard";
import { AppShell } from "@/components/app-shell";

export const dynamic = "force-dynamic";

export default async function Page() {
  const u = await requireUser(["ADMIN"]);
  const { data: categories } = await u.supabase.from("categories").select("*,subcategories(*)").order("sort_order");

  return <AppShell user={u.profile}>
    <div className="pagehead"><div><p className="eyebrow">Inspection setup</p><h1>Categories</h1><p className="muted">Create multiple categories, map subcategories, and manage the whole taxonomy from one page.</p></div><a className="btn btn-primary" href="#create-category">Add category</a></div>
    <section className="card"><h2>Import categories and subcategories</h2><p>Download the CSV template and enter one category/subcategory pair per row. Repeat a category to map multiple subcategories. The mapping is available to every inspecting user. Repeated names update the existing category or subcategory instead of creating duplicates. Subcategories are matched within their parent category.</p><DownloadButton href="/api/admin/categories" filename="category-mapping.csv">Download mapping format</DownloadButton><AdminForm action="/api/admin/categories" method="post"><div className="field"><label>Mapping CSV</label><input type="file" name="file" accept=".csv,text/csv" required /></div><button className="btn btn-primary">Upload categories and subcategories</button></AdminForm></section><div className="grid2" id="create-category"><AdminForm className="card" action="/api/admin/master" method="post"><p className="eyebrow">Parent level</p><h2>Create categories</h2><input type="hidden" name="kind" value="category" /><div className="field"><label>Category names</label><textarea name="names" placeholder="One category per line" required /></div><button className="btn btn-primary">Add categories</button></AdminForm><AdminForm className="card" action="/api/admin/master" method="post"><p className="eyebrow">Child level</p><h2>Map subcategories</h2><input type="hidden" name="kind" value="subcategory" /><div className="field"><label>Category</label><select name="categoryId" required><option value="">Select category</option>{categories?.map((category: any) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></div><div className="field"><label>Subcategory names</label><textarea name="names" placeholder="test1, test2, test3" required /></div><button className="btn btn-primary">Add subcategories</button></AdminForm></div>
    <section className="card"><div className="section-heading"><div><p className="eyebrow">Project inspection taxonomy</p><h2>All categories</h2></div><span className="badge">{categories?.length || 0} categories</span></div><div className="taxonomy-list">{categories?.map((category: any) => <details className="taxonomy-item" key={category.id}><summary className="taxonomy-head"><span><h3>{category.name}</h3><small>{category.subcategories?.length || 0} mapped subcategories</small></span><span className="summary-action">View / edit</span></summary><div className="taxonomy-body"><AdminForm className="inline-edit" action="/api/admin/master" method="post"><input type="hidden" name="action" value="update" /><input type="hidden" name="kind" value="category" /><input type="hidden" name="id" value={category.id} /><div className="field"><label>Category name</label><input name="name" defaultValue={category.name} required /></div><button className="btn btn-secondary">Save category</button></AdminForm><div className="sub-list">{(category.subcategories || []).map((item: any) => <details className="sub-row" key={item.id}><summary><span>{item.name}</span><span className="summary-action">Edit</span></summary><AdminForm className="inline-edit" action="/api/admin/master" method="post"><input type="hidden" name="action" value="update" /><input type="hidden" name="kind" value="subcategory" /><input type="hidden" name="id" value={item.id} /><div className="field"><label>Subcategory name</label><input name="name" defaultValue={item.name} required /></div><div className="row-actions"><button className="btn btn-primary">Save subcategory</button></div></AdminForm><AdminForm action="/api/admin/master" method="post"><input type="hidden" name="action" value="delete" /><input type="hidden" name="kind" value="subcategory" /><input type="hidden" name="id" value={item.id} /><button className="btn btn-danger">Delete</button></AdminForm></details>)}</div><AdminForm action="/api/admin/master" method="post"><input type="hidden" name="action" value="delete" /><input type="hidden" name="kind" value="category" /><input type="hidden" name="id" value={category.id} /><button className="btn btn-danger">Delete category</button></AdminForm></div></details>)}</div></section>
  </AppShell>;
}
